# Generated by Django 2.2.5 on 2020-05-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
