# Generated by Django 2.2.5 on 2020-05-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
